### ISSUE TITLE
ImportError: No module named Crypto.Cipher

### ISSUE THREAD

**Issue by eBug** [zoobab/EMVCAP#2]
After upgrading my system de Debian 11 and python3, I get that error:
```
/usr/local/bin/EMV-CAP 
Traceback (most recent call last):
  File "/usr/local/bin/EMV-CAP", line 58, in <module>
    from EMVCAPfoo  import *
  File "/usr/local/lib/python2.7/dist-packages/EMVCAPfoo.py", line 2, in <module>
    from EMVCAPcore import hex2lint
  File "/usr/local/lib/python2.7/dist-packages/EMVCAPcore.py", line 2, in <module>
    from Crypto.Cipher import DES
ImportError: No module named Crypto.Cipher

```
even after installing pycrypto:
```
pip install pycrypto
Collecting pycrypto
  Downloading pycrypto-2.6.1.tar.gz (446 kB)
     |████████████████████████████████| 446 kB 4.4 MB/s 
Building wheels for collected packages: pycrypto
  Building wheel for pycrypto (setup.py) ... done
  Created wheel for pycrypto: filename=pycrypto-2.6.1-cp39-cp39-linux_x86_64.whl size=526405 sha256=2e1d3d539ed972aa772c15d39ad8d30229fdbdeae2cd70f28623663ed50ff060
  Stored in directory: /root/.cache/pip/wheels/9d/29/32/8b8f22481bec8b0fbe7087927336ec167faff2ed9db849448f
Successfully built pycrypto
Installing collected packages: pycrypto
Successfully installed pycrypto-2.6.1
```

**Comment by eBug** [comment]
I guess there was some mess after keeping both python2 and python3 installed. pip3 installed Crypto module for python3.
